### ISSUE TITLE
Match DoU with Marcello's definition

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/2BURP#45]
Marcello will send their code

**Comment by cjacobscrisioni** [comment]
Many improvements, and we are getting close... however some stubborn differences remain. See comparison attached.

- Smoothing of urban centres seems to be more extensive in the GHSL product than in the procedures within 2BURP
- The procedure allocates rural clusters adjacent to urban centres, which seems wrong.

Causes may be conversion from Mollweide to LatLong, or misinterpretation from the available documentation. 

I suggest we 
- Make a standalone application using a mollweide grid, so that effects from conversion are avoided
- Ask more clarification from the expert (Marcello Schiavina) when he is available


![Ruhr_area](https://github.com/ObjectVision/2BURP/assets/144823297/7a5f3f43-53dd-4a1e-aa84-cbaf855d8524)

**Comment by cjacobscrisioni** [comment]
Just pushed a new version of the isolated degree of urbanisation approach... Results much better but still some doubts:

- Urban centre smoothing inconsistent and somewhat unclear
- In cascade, some unclarity re: dense urban clusters close to urban centres
- semi-dense urban clusters sometimes take over entire urban cluster in the original degree of urbanisation data. But unsure if the latter already includes the latest results from changes to the sduc

See picture below for comparison. 

The code also still needs cleaning.. ie
- Better to create one general bucket of parameters as the flow is much more cascading then isolated
- The Dense_urban_cluster container may be renamed to Urban_Clusters, as only urban clusters (and in cascade rural clusters) are separated there.
- The dense urban clusters are already identified in the urban centres container now.


![Ruhr_area_iter2](https://github.com/ObjectVision/2BURP/assets/144823297/bd4f154d-990c-46b2-a4d2-1a3a132732d8)

**Comment by cjacobscrisioni** [comment]
Current accuracy of reproduction seems accurate. I have received a more recent degurba file from Marcello which should be even more similar. Known issues with current implementation:
- Smoothing is slow. As the match does not have to be perfect, maybe we can reduce the number of smoothing iterations.
- I am getting implausible urban coastlines generally in the projections (see South America below). This is either an issue with the degurba way of treating densities or an issue with the population allocation.
- 
![image](https://github.com/ObjectVision/2BURP/assets/144823297/73612f28-909e-4618-acb5-316667a324b8)

**Comment by cjacobscrisioni** [comment]
Issue comes into play after 2020; so it is not the degree of urbanisation method per se
